# Site settings
title: Perry Rivera
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learn about candidate Perry Rivera in these links.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pvrconsulting
github_username:  perryrivera

# Build settings
markdown: kramdown
